version: "3.8"

services:
  telegram-notion-bot:
    build: .
    container_name: telegram_notion_bot
    env_file:
      - .env  # Load environment variables from .env file
    restart: unless-stopped  # Auto-restart on crash, but not on manual stop
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Optional: map a volume if needed (e.g., logs or configs)
    # volumes:
    #   - ./logs:/app/logs
